.PHONY: clean All

All:
	@echo "----------Building project:[ Shapes - Debug ]----------"
	@cd "Shapes" && "$(MAKE)" -f  "Shapes.mk"
clean:
	@echo "----------Cleaning project:[ Shapes - Debug ]----------"
	@cd "Shapes" && "$(MAKE)" -f  "Shapes.mk" clean
