.PHONY: clean All

All:
	@echo "----------Building project:[ CPPProject - Debug ]----------"
	@cd "CPPProject" && "$(MAKE)" -f  "CPPProject.mk"
clean:
	@echo "----------Cleaning project:[ CPPProject - Debug ]----------"
	@cd "CPPProject" && "$(MAKE)" -f  "CPPProject.mk" clean
